### ISSUE TITLE
Blaine county savings

### ISSUE THREAD

**Issue by TheRealCrappyGamer** [Knaak53/esx_knatusrobberybank#13]
I noticed when downloading this that blaine county savings is commented out. When Uncommenting it, I can't find anything wrong except that the gate isn't locked by default. When trying to use esx_doorlock to lock it, it locks it but it doesn't reset it to 0 position when it locks it, so it locks it partially open. Any way to fix it in the bank robbery script?

**Comment by Knaak53** [comment]
Blaine country is commented by the way, and the reason is that you say.

So, Blaine country is not supported at this version, maybe at new updates, im working on it when i have time.

**Comment by TheRealCrappyGamer** [comment]
Yeah, I was trying to get it working but can't get the rotation of the gate to work. I also can't seem to start the vault door as closed to begin with. I was going to fix it up and do a pull request, as well as add the other fleeca banks but it seemed like the code was built to only support the banks you have in the config.
