### ISSUE TITLE
Using esx_doorlock the door is bug 

### ISSUE THREAD

**Issue by DoradoRodriguez** [Knaak53/esx_knatusrobberybank#18]
using esx_doorlock the door block but is open 

example
https://drive.google.com/file/d/1lpzxUeH8FzafO1Wg9nHMKRqCRcsyRNS_/view?usp=sharing

	**-- principal bank
	{
		objName = 'hei_v_ilev_bk_gate2_pris',
		objCoords  = {x = 261.99899291992, y = 221.50576782227, z = 106.68346405029},
		textCoords = {x = 261.99899291992, y = 221.50576782227, z = 107.68346405029},
		authorizedJobs = { 'police' },
		locked = true,
		distance = 12,
		size = 2
	},**

script say error because not vector3 on coords 

can you tell me with esx_doorlock version this works?

my esx_doorlock version 

description 'ESX Door Lock'

version '1.4.0'

ty :D

**Comment by Knaak53** [comment]
Just convert it to vector3

`**-- principal bank
{
	objName = 'hei_v_ilev_bk_gate2_pris',
	objCoords  = vector3(261.99899291992, 221.50576782227, 106.68346405029),
	textCoords = vector3(261.99899291992, 221.50576782227, 107.68346405029),
	authorizedJobs = { 'police' },
	locked = true,
	distance = 12,
	size = 2
},**`
