### ISSUE TITLE
Door isn't locked

### ISSUE THREAD

**Issue by UKRP1** [Knaak53/esx_knatusrobberybank#2]
Surely we must need to add something to this bank door for the hacking, as its currently open, and no hint for lock/unlock

**Comment by Knaak53** [comment]
I did it as a open "force" more than lock/unlock hacking, but you can easily modify it calling to esx_doorlock event at esx_holdupbank:opendoors event instied the sync force logic

**Comment by Knaak53** [comment]
I close this issue due is not a error, just a different way to work
