### ISSUE TITLE
Welding never stops

### ISSUE THREAD

**Issue by UKRP1** [Knaak53/esx_knatusrobberybank#3]
Welding doesnt stop after successful robbery

**Comment by Knaak53** [comment]
Should work with the last commit

**Comment by LividFizz** [comment]
stops 1 minute after the robbery is complete. Still does not "work" but it does stop

**Comment by markmorris** [comment]
yeah still having this issue, sometimes it just doesnt work either.

**Comment by Knaak53** [comment]
Should be fixed wit the last merge
