### ISSUE TITLE
Doors do not close

### ISSUE THREAD

**Issue by LividFizz** [Knaak53/esx_knatusrobberybank#4]
Bank vault and Fleeca bank does not close after robbery. Is this an issue on my end?

**Comment by Knaak53** [comment]
Please, read this explanation how the door is closed at the oficial post:

https://forum.fivem.net/t/release-esx-new-reworked-bank-robbery-system/552522/55?u=knatus53


Summary is: When you got far from the bank, it is closed auttomatically.
