### ISSUE TITLE
The hacking gate door isn't locked

### ISSUE THREAD

**Issue by UKRP1** [Knaak53/esx_knatusrobberybank#6]
So with esx_doorlock

how do we know the coords / to make the gate unlock to get to the vault once hacking is completed ?

At present, it is unlocked whether you hack it or not, allowing people just to run straight for the vault to place c4

**Comment by Knaak53** [comment]
Use this config part to use at your esx_doorlock

```
-- principal bank
	{
		objName = 'hei_v_ilev_bk_gate2_pris',
		objCoords  = {x = 261.99899291992, y = 221.50576782227, z = 106.68346405029},
		textCoords = {x = 261.99899291992, y = 221.50576782227, z = 107.68346405029},
		authorizedJobs = { 'police' },
		locked = true,
		distance = 12,
		size = 2
	},
```
